//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bellini.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bellini.Tests.MockResponses", typeof(MockResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;count&quot;: 2,
        ///  &quot;href&quot;: &quot;/guestAuth/app/rest/builds?locator=buildType:MyTest_BuildType1&quot;,
        ///  &quot;build&quot;: [
        ///    {
        ///      &quot;id&quot;: 1,
        ///      &quot;buildTypeId&quot;: &quot;MyTest_BuildType1&quot;,
        ///      &quot;number&quot;: &quot;2&quot;,
        ///      &quot;status&quot;: &quot;SUCCESS&quot;,
        ///      &quot;state&quot;: &quot;finished&quot;,
        ///      &quot;branchName&quot;: &quot;master&quot;,
        ///      &quot;defaultBranch&quot;: true,
        ///      &quot;href&quot;: &quot;/guestAuth/app/rest/builds/id:1&quot;,
        ///      &quot;webUrl&quot;: &quot;http://teamcity/viewLog.html?buildId=1&amp;buildTypeId=MyTest_BuildType1&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 2,
        ///      &quot;buildTypeId&quot;: &quot;MyTest_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Builds {
            get {
                return ResourceManager.GetString("Builds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;count&quot;: 2,
        ///  &quot;href&quot;: &quot;/guestAuth/app/rest/buildTypes/?locator=project:MyTest&quot;,
        ///  &quot;buildType&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;BuildTypeOne&quot;,
        ///      &quot;name&quot;: &quot;Buildtype One&quot;,
        ///      &quot;projectName&quot;: &quot;My Test&quot;,
        ///      &quot;projectId&quot;: &quot;MyTest&quot;,
        ///      &quot;href&quot;: &quot;/guestAuth/app/rest/buildTypes/id:MyTest_BuildTypeOne&quot;,
        ///      &quot;webUrl&quot;: &quot;http://teamcity/viewType.html?buildTypeId=MyTest_BuildTypeOne&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;BuildTypeTwo&quot;,
        ///      &quot;name&quot;: &quot;Buildtype Two&quot;,
        ///      &quot;projectName&quot;: &quot;My Test&quot;,
        ///      &quot;project [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildTypes {
            get {
                return ResourceManager.GetString("BuildTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;count&quot;: 327,
        ///  &quot;href&quot;: &quot;/guestAuth/app/rest/projects&quot;,
        ///  &quot;project&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;_Root&quot;,
        ///      &quot;name&quot;: &quot;&lt;Root project&gt;&quot;,
        ///      &quot;description&quot;: &quot;Contains all other projects&quot;,
        ///      &quot;href&quot;: &quot;/guestAuth/app/rest/projects/id:_Root&quot;,
        ///      &quot;webUrl&quot;: &quot;http://teamcity/project.html?projectId=_Root&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: &quot;TestProject&quot;,
        ///      &quot;name&quot;: &quot;Test Project&quot;,
        ///      &quot;parentProjectId&quot;: &quot;_Root&quot;,
        ///      &quot;description&quot;: &quot;Test Project Description&quot;,
        ///      &quot;href&quot;: &quot;/guestAuth/app/rest/proj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
    }
}
